services:
  abstractgo-server:
    container_name: abstractgo-server
    image: python:3.12-slim
    command: sh -c "bash /code/server-entrypoint.sh"
    volumes:
      - ../server:/code
      - ../server/requirements.txt:/code/requirements.txt
      - ../saved_models:/code/saved_models
      - ./server-entrypoint.sh:/code/server-entrypoint.sh
    environment:
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - APP_DOMAIN_NAME=${APP_DOMAIN_NAME}
      - APP_NAME=${APP_NAME}
      - ORG_NAME=${ORG_NAME}
      - SERVER_DEBUG=${SERVER_DEBUG}
      - BASE_MODEL_NAME=${BASE_MODEL_NAME}
      - CLOUD_MODEL_NAME=${CLOUD_MODEL_NAME}
      - USE_LOCAL_MODEL=${USE_LOCAL_MODEL}
      - LOCAL_MODEL_PATH=${LOCAL_MODEL_PATH}
      - LOCAL_MODEL_TOKENIZER_PATH=${LOCAL_MODEL_TOKENIZER_PATH}
      - HF_TOKEN=${HF_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - AIMLAPI_API_KEY=${AIMLAPI_API_KEY}
      - AIMLAPI_BASE_URL=${AIMLAPI_BASE_URL}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS}
      - LLM_TOP_P=${LLM_TOP_P}
      - LLM_SEED=${LLM_SEED}
    ports: ["8000:8000"]
    networks:
      - my_shared_network

  abstractgo-client:
    container_name: abstractgo-client
    image: nginx:alpine
    volumes:
      - ../client/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports: ["3000:80", "3001:443"]
    depends_on: [abstractgo-server]
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true # Reference the same external network as the other services
