services:

  abstractgo-server:
    container_name: abstractgo-server
    build:
      context: ..
      dockerfile: Dockerfile
    working_dir: /code
    command: sh -c "python api/main.py"
    volumes:
      - ../server/api:/code/api
    environment:
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports: ["8000:8000"]
    networks:
      - my_shared_network

  abstractgo-client:
    container_name: abstractgo-client
    image: nginx:alpine
    volumes:
      - ../client/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    # ports: ["80:80", "443:443"]
    ports: ["8087:80"]
    depends_on: [abstractgo-server]
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true # Reference the same external network as the other services
