services:

  abstractgo-server:
    container_name: abstractgo-server
    image: python:3.12-slim
    command: sh -c "bash /code/server-entrypoint.sh"
    volumes:
      - ../server/api:/code/api
      - ../server/requirements.txt:/code/requirements.txt
      - ../saved_models:/code/saved_models
      - ./server-entrypoint.sh:/code/server-entrypoint.sh
    environment:
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports: ["8000:8000"]
    networks:
      - my_shared_network

  abstractgo-client:
    container_name: abstractgo-client
    image: nginx:alpine
    volumes:
      - ../client/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports: ["3000:80", "3001:443"]
    depends_on: [abstractgo-server]
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true # Reference the same external network as the other services
